# fly.toml app configuration file generated for abdurrahmaan9-portfolio on 2025-06-14T16:08:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'abdurrahmaan9-portfolio'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
